### ISSUE TITLE
光13 BOSS 卡戴斯的被动”最大生命值等比伤害减免50%“导致伤害计算不准确的问题

### ISSUE THREAD

**Issue by hsj1992** [Icetail1/ICE-Calculate#2]
以注视者修里为例，
愤怒套，加攻BUFF；
面板为3644攻击力，341暴击伤害；
阵型加成和攻击加成分别为10.2、10；
佩戴神器为30满级白日梦小丑。

卡戴斯在标靶状态下，计算器输出的满级S3伤害是 103004；
实际游戏里是 80569，如图所示：
![Screenshot_2022 12 21_22 20 44 352](https://user-images.githubusercontent.com/4816005/208928199-869a9301-74f7-4fd3-95a8-97d2f71a8b78.png)

假设因为BOSS的被动，满级白日梦实际效果等于0级白板白日梦，也就是1.5%，
若将计算器中白日梦等级调到0，得出的S3伤害为80805，该结果更为接近实际数值80569。

**Comment by Icetail1** [comment]
已解决。加了一个百分比增伤效果。
